spring.application.name=demosecurity
spring.security.user.name=vinay1
spring.security.user.password=12345

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
